language: java

jdk:
  - oraclejdk8

deploy:
  provider: openshift
  user:
    secure: "oQP7lnC39jQAyyJYsqXV7SWiHgFOc3J6/EZXehRd8/d3Coe8qojqz9o1Z8a4ws+LhkPZnG24WhstwYC6AafrXEBf8xBWNXoBvceecWMHBTaVWnrZUEIjJ3TurlqbwwPhzIordB8n3FXpEnsMetLib31HhZvzlbjhIA3i2fJeedW6zuSZU5djz/FYJtODOu3LQ2DCs3SSsDXdtpJWNKzT8WwIzouOp9RRyHtlJunrNpLN1OYaFcwMBEII7O2f8ZqzIP189BYJv0EtGoAcCrDDEBb/B0RWZHfCF6Cz8XWEpCrK4nmGJDGwLA4PuVTn1hg0sfVbqLOoqd74Dre6XMfCzp1DmKlBMn8LCHKCs332kMqvontOguTX669LcQ33OQgmfQwKnsHrCDJzQSruSlr44248DbBAn0goe0ZSxYf1HAVJYDzMyfsghk76zCsGV4jbKepNuPi+aPNHk0USxIwG+nXT0SDFZxnm+RaG74Qll827feBoK/9wBojWBGBaFe4dBljf1xniktnlPnvAXeNJMVs23J/m+/1WOA9UF9dWQz2rggoy8Au3R1gQTgbi0Kmu7x9HI1DzcJBCVczVjB43lz5RymZY8Ji8nGKZsCtw0fLEenrV2OnmIiz2zQaBEpQSyn2Qy3rfZvTCt6I5XsmgJg2ueZZo/L38v4xs5Gf3WCo="
  password:
    secure: "JfalsZiPRFdPlkLpuV6mFPFVedkCF0O6k/1zP/FWlAt5FLVDZS7kELS812O0AC34gKdfs8nyZQ+EjEf6Bng5gnewZgnAvX2Iqj6LIZimlNT5u+GgcSCcyWIidz7NwdlFfy1XVb+RiuJQRdr1nrU9P4Jzj5woQFkLnRvgRWpgcAUTA/WdhioogON+n91h36E905ipcdHHnzcHOzeJCdRmRwUFJkAOY+W3LUFnRelg1MjDygxDUT8kk3X4pjfMrOfi+9dvG84o8nCgUfNpFGV+a+r+ieI7bF6t9LkKkNF7ufhAGIJTp9Dg/sji1sIGd52J4Odc4umK2XQQ/nox9+MJ4jqWKBothkpE7ULoyYuWRQgvozVvkXjXNAvbtmFeLUcPus6PLvXos74vJlme4IqTM5saIqDGw+qvLlGzlL3MrFIagb8f/NDBE6G5QBw6cZe1cKH813ou9OLo6hPCt9T3JIAWoMsquc+MvGdle+jQgoXnr5HppKVyzsDF9abyVW2zLJ6fIXXOz6vu+2B57Gktld0/3e0DQI/2I2tooOd7vJ36VzC8s8hrhlaFMPICn5M5EAmWLMGtclQXnuxz3TjxofoUL41+FD8S5p0Iz9yngvzLwTlY+r4ntgX7dEpwQ2CD2serZ32OXB1tA88mVvWPWlWDvW+91nlwLDQCkusrSlI="
  domain: "munchkincounterw"
